### PR TITLE
Remove the mention of Combustion Turbines from Oil Burners

### PR DESCRIPTION
**Pull request by have-fun-was-taken**
Combustion Turbines were removed, so it's reasonable to remove their mention from the tooltip of the Oil Burner.

### CODE REVIEW

**Comment by notnotmelon** [comment]
Merged. Thank you

**Comment by notnotmelon** [comment]
Please update the changelog for future PRs

**Comment by have-fun-was-taken** [comment]
Do you mean adding something to [changelog.txt](https://github.com/pyanodon/pypetroleumhandling/blob/master/changelog.txt) ?

**Comment by notnotmelon** [comment]
Yes. It's important to keep a good record.

**Comment by notnotmelon** [comment]
Unfortunately, none of the mods have PR instructions. It would be helpful to have, an issue would be appreciated.

**Pull request merged**
