### PR TITLE
Update base-updates.lua

### PR DESCRIPTION
**Pull request by Erkigmo**
Helps me with updating PyCoalTBaA.

### CODE REVIEW

**Comment by Erkigmo** [comment]
I'm able to load Factorio Py AE, something is wrong with the tests then

**Comment by oorzkws** [comment]
Since you're already writing PyCoalTBA, why aren't you making this change there? Just curious, it seems like it should be done in the compat mod

**Comment by Erkigmo** [comment]
I don't know how I'd do it in another mod.

**Comment by Erkigmo** [comment]
Ok I know how I'd do it in PyCoalTBaA, but it is so much easier to do it here.

**Comment by notnotmelon** [comment]
Only 4 lines are needed. Add this code to pYCoalTBA

data.lua

`
local stone = table.deepcopy(data.raw.resource['angels-ore-1'])
stone.name = 'stone'
data:extend{stone}
`

data-updates.lua
`
data.raw.resource['stone'] = nil
`

I'm not 100% sure if angels-ore-1 is the correct prototype name. Make sure to double check this.
Hope it helps!

**Comment by Erkigmo** [comment]
image

**Comment by Erkigmo** [comment]
I think I found out why it wasn't working; PyCoalTBaA got unloaded

**Comment by Erkigmo** [comment]
It still isn't working, same error message

**Comment by Erkigmo** [comment]
So can we do this? It looks really hard to do it through PyCoalTBaA, and Arthur said the issue is just down to us not checking stone exists, which would cause a load error on its own.

**Comment by Erkigmo** [comment]
Thanks!

**Pull request closed without merging**
